### ISSUE TITLE
Move contextual menu items to command palette

### ISSUE THREAD

**Issue by daeh** [stneveadomi/grepc#104]
The `grepc` contextual menu items take up a lot of space and don't seem specific to the code that was right-clicked. If these commands are not context-specific, I'd think that they should be in the command palette rather than the contextual menu. And if they should stay in the contextual menu for some reason, then maybe consider at least grouping them into a submenu. (But I'd opt for the command palette if possible!)

![CleanShot 2024-08-28 at 21 10 21](https://github.com/user-attachments/assets/b761d770-5abd-499b-8642-cfa0c2f0aa30)

**Comment by stneveadomi** [comment]
Very good point, I was thinking of this the other day. The only "contextual" command is creating a rule from selection. This is luckily an easy fix.
