### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by daeh** [stneveadomi/grepc#88]
Hi — I'm trying this plugin out and am finding it to be substantially more fickle than the other RegExp highlighters I've used. 

Two things I'm noticing a lot are (1) that the highlight does not show up until the cursor has moved past a pattern, and (2) that there can be highlight artifacts after a pattern no longer exists.

Here's a couple examples. I have highlights on `model` and `empir`. In the first screenshot, I've typed `model` and the cursor is at the `l`, but the highlight has not appeared. 

![CleanShot 2024-07-13 at 02 39 44@2x](https://github.com/user-attachments/assets/297c5556-6cdf-4551-9fda-5f9d8dbaa052)

In the second screenshot the cursor is actually a space past the the end of the word and the highlight still hasn't appeared (this behavior is less common but does occur). 

![CleanShot 2024-07-13 at 02 36 37@2x](https://github.com/user-attachments/assets/d32e6955-0bc6-4e04-9e6e-dcc637f498c4)

In the third, I've deleted `empir` but the border is still being drawn on the place where the pattern started.

![CleanShot 2024-07-13 at 02 36 00@2x](https://github.com/user-attachments/assets/9c41c1c3-413b-4a56-95e3-a14ee0099c21)

Plugin is off to to great start!

**Comment by stneveadomi** [comment]
Hi! Thank you for trying out the plugin and reporting an issue :) really appreciate it

I will prioritize these for the next release as I have also noticed some of these.

**Comment by stneveadomi** [comment]
@daeh let me know if with the new release you find the performance improved. If you find any more issues with this, feel free to leave another issue. Really appreciate the contributions to the project :)
